### ISSUE TITLE
missing UNUserNotificationCenterDelegate methods

### ISSUE THREAD

**Issue by Megal** [pchelnikov/PluggableAppDelegate#11]
Method implemented in plugin is not being called:

 `
    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void
    ) {
`

**Comment by Tawfikk** [comment]
When will you fix this bug ? @pchelnikov

**Comment by pchelnikov** [comment]
@Megal @Tawfikk PR is merged
