### ISSUE TITLE
UIBackgroundModes opt-out

### ISSUE THREAD

**Issue by kirualex** [pchelnikov/PluggableAppDelegate#2]
It would be interesting to find a way to prevent those warnings to appear, as well as the iTunes Connect warnings when uploading a build, for developers not requiring these features.

```
You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], 
but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.

You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], 
but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
```

**Comment by hashemp206** [comment]
its only a warning. 
there should be a check if user has not enabled some features, corresponding app delegates method should not be called
