### ISSUE TITLE
Xcode 10 Swift 4.2 not recognized

### ISSUE THREAD

**Issue by dermaaarkus** [pchelnikov/PluggableAppDelegate#7]
Hi,

thanks for your lib/fork!

When i use it with cocoapods and refer to the master branch, i get the hint to upgrade to Swift 4.2 all the time. I did a screenshot. In my opinion there is something wrong with your project file (because your code is Swift 4.2), but i am not 100% sure what todo. Can you please take a closer look?

<img width="1207" alt="bildschirmfoto 2019-03-06 um 00 10 37" src="https://user-images.githubusercontent.com/7196958/53844133-179f9980-3fa5-11e9-9746-e5d124a7e5aa.png">

**Comment by pchelnikov** [comment]
@dermaaarkus hi,

ah, I think an issue in podspec file. Will fix this in a while.

Thank you for reporting.

**Comment by pchelnikov** [comment]
@dermaaarkus I've just updated the pod. Could you please check and write to me if this works or not.

**Comment by dermaaarkus** [comment]
It works for me, thanks a lot! 👍
